version: "3.3"
services:
  api:
    image: test-api
    build: api/
    container_name: test_api
    ports:
      - "3000:3000"


  notes:
    image: test-notes
    build: notes/
    container_name: test_notes
    ports:
      - "80:8080"